Fp/local kindle gen
guardian/kindle-gen pull request #56
Opened 2021-06-21 11:28 UTC by Fweddi

## What does this change?
This PR allows a developer to run the kindle-gen lambda locally, provided they use the correct configuration settings.

## How to test
Follow the instructions in [the README](https://github.com/guardian/kindle-gen/blob/fp/local-kindle-gen/README.md#running-locally) so that you are using the right configuration settings and local environment.

Use `sbt run` to run the lambda, and inspect the CODE S3 bucket to see the uploaded output.

## How can we measure success?
The lambda should execute without error, and upload correctly formatted kindle data to the DEV folder in the CODE S3 bucket.

## Have we considered potential risks?
Pointing to the production bucket could risk the Kindle publishing unintended data, so be sure to follow the instructions in the README closely.

Excessive use of keys used in production (e.g. Accuweather has the same key for PROD and CODE, which I used locally) could cause us to reach the rate limit for that key. Ideally, we would have separate keys for different environments, but so far I have been unable to track down who maintains our relationship with Accuweather (this service is used by many applications in different teams).

2021-06-21 11:44 UTC, Fweddi commented on src/main/scala/com/gu/kindlegen/app/Settings.scala
> +  private final val Environment = "prefix"
I've elected to use the S3 folder prefix to define the environment, as (a) this variable needs to be set to PROD / CODE / DEV, and (b) it eliminates the need to add another environment variable to our build.

Am happy to add a new config variable if it's desirable.

2021-06-22 10:06 UTC, JustinPinner requested changes
I wonder if most of this can be done without changing the main lambda or settings reader quite so much (or at all). Let's chat about it?

2021-06-22 15:06 UTC, NathanielBennett commented on src/main/scala/com/gu/kindlegen/LocalRun.scala
> +}
:+1: Good implementation. Provides you with what you need with minimal clutter. Ensures you bail if anything goes wrong

2021-06-22 19:34 UTC, regiskuckaertz reviewed
Hello 👋

2021-06-22 19:34 UTC, regiskuckaertz commented on src/main/scala/com/gu/kindlegen/app/Lambda.scala
> +          case Failure(e) => logger.warn("Publishing the zip archive failed!", e)
Surely The publisher should be closed here as well? Otherwise you risk leaking resources.

2021-06-22 19:34 UTC, regiskuckaertz commented on src/main/resources/reference.conf
> +  url = "https://preview.content.guardianapis.com"
😲 this public?

2021-06-23 09:49 UTC, closed without merging